pipeline {
    agent any

    environment {
        IMAGE_NAME = "taskflow-app"
        CONTAINER_NAME = "taskflow-test"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t ${IMAGE_NAME} -f docker/Dockerfile .
                '''
            }
        }

        stage('Test Application') {
            steps {
                sh '''
                docker rm -f ${CONTAINER_NAME} || true

                docker run -d --name ${CONTAINER_NAME} ${IMAGE_NAME}

                echo "Waiting for application to start..."

                sleep 10

                docker logs ${CONTAINER_NAME}

                docker run --rm \
                  --network container:${CONTAINER_NAME} \
                  curlimages/curl \
                  -f http://localhost:5000/health
                '''
            }

            post {
                always {
                    sh '''
                    docker stop ${CONTAINER_NAME} || true
                    docker rm ${CONTAINER_NAME} || true
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                cd docker

                docker compose down || true

                docker compose up -d --build

                sleep 5

                curl -f http://localhost:5000/health
                '''
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully"
        }

        failure {
            echo "Pipeline failed"
        }
    }
}
